service: kpi-test-superset-generateccd
frameworkVersion: '3'
package:
  exclude:
    - ./**
  include:
    - es_controller.py
    - lambda_function.py
provider:
   name: aws
   stage: prod
   region: us-east-1
   runtime: python3.7
   lambdaHashingVersion: 20201221
   deploymentBucket: kpi-test-lambda
   iam:
      role: arn:aws:iam::527774997072:role/service-role/kpi-dev-inbound-decrypt-role-x94sy5af
   apiGateway:
     restApiId: 7yk7kpewvi
     restApiRootResourceId: eshblsd0f6
     restApiResources:
       '/EncounterSearch': post
	 
functions:
  GenerateCCD:
    handler: lambda_function.lambda_handler
    role: arn:aws:iam::527774997072:role/service-role/kpi-dev-inbound-decrypt-role-x94sy5af
    name: kpi-test-superset-GenerateCCD
    events:
      - http:
          path: /GenerateCCD
          method: post
          cors: true
          authorizer:
            name: kpi-dev-authorization
            type: COGNITO_USER_POOLS
            arn: arn:aws:cognito-idp:us-east-1:527774997072:userpool/us-east-1_QYPRYHUOv
